### ISSUE TITLE
arxan SIG fails match on BO3

### ISSUE THREAD

**Issue by Cryptiiiic** [OhItsDiiTz/idc-scripts#1]
Here's the fix `"8B 45 ? 83 F8 FF 0F 85 ? ? ? ? E9 ? ? ? ?"`

**Comment by OhItsDiiTz** [comment]
> Here's the fix `"8B 45 ? 83 F8 FF 0F 85 ? ? ? ? E9 ? ? ? ?"`

which build of bo3 did you try it on? because the sig I supplied worked just fine for the arxan script.

**Comment by Cryptiiiic** [comment]
Sorry I'm not sure, maybe I accidentally was using an already unpacked/patch exe? I looked and the cod build date is this.
Fri Dec 13 18:25:43 2019

**Comment by OhItsDiiTz** [comment]
> 

Might be why, I used a build that was older lol.
